export const SETTING_CHANNEL = 'SETTINGS';

export const SETTING_KEYS = {
  SITE_NAME: 'siteName',
  LOGO_URL: 'logoUrl',
  FAVICON: 'favicon',
  REQUIRE_EMAIL_VERIFICATION: 'requireEmailVerification',
  ADMIN_EMAIL: 'adminEmail',
  SENDER_EMAIL: 'senderEmail',
  META_KEYWORDS: 'metaKeywords',
  META_DESCRIPTION: 'metaDescription',
  HEADER_SCRIPT: 'headerScript',
  AFTER_BODY_SCRIPT: 'afterBodyScript',
  MONTHLY_SUBSCRIPTION_COMMISSION: 'monthlySubscriptionCommission',
  YEARLY_SUBSCRIPTION_COMMISSION: 'yearlySubscriptionCommission',
  VIDEO_SALE_COMMISSION: 'videoSaleCommission',
  PRODUCT_SALE_COMMISSION: 'productSaleCommission',
  TIP_COMMISSION: 'TipCommission',
  GALLERY_SALE_COMMISSION: 'gallerySaleCommission',
  CCBILL_SUB_ACCOUNT_NUMBER: 'ccbillSubAccountNumber',
  CCBILL_PUR_ACCOUNT_NUMBER: 'ccbillPurAccountNumber',
  CCBILL_FLEXFORM_ID: 'ccbillFlexformId',
  CCBILL_SALT: 'ccbillSalt',
  CCBILL_HONEYDRIP_SUB_ACCOUNT_NUMBER: 'ccbillHoneyDripSubAccountNumber',
  CCBILL_HONEYDRIP_PUR_ACCOUNT_NUMBER: 'ccbillHoneyDripPurAccountNumber',
  USE_SENDGRID_TRANSPORTER: 'useSengridTransporter',
  SMTP_TRANSPORTER: 'smtpTransporter',
  SENDGRID_API_KEY: 'sendgridApiKey',
  GOOGLE_ANALYTICS_CODE: 'gaCode',
  MAINTENANCE_MODE: 'maintenanceMode',
  COUPON_SWITCH: 'couponSwitch',
  NUDIRTY_SWITCH: 'nudirtySwitch',
  NUDIRTY_MIN_SCORE: 'nudirtyMinScore',
  RIGHT_CLICK_PRINT_SWITCH: 'rightClickPrintSwitch',
  CCBILL_CLIENT_ACCOUNT_NUMBER: 'ccbillClientAccountNumber',
  VIEW_PORT_CONTENT: 'viewPortContent',
  SCREEN_ORIENTATION: 'screenOrientation',
  TIP_SWITCH: 'tipSwitch',
  SHOP_CART_SWITCH: 'shopCartSwitch',
  MIN_VISIBLE_SUBSCRIBERS_COUNT: 'minVisibleSubscribersCount',
};

export const MENU_SECTION = {
  MAIN: 'main',
  HEADER: 'header',
  FOOTER: 'footer'
};
