export const EMAIL_OR_PASSWORD_INCORRECT = 'Email or password is incorrect';
export const USERNAME_OR_PASSWORD_INCORRECT = 'Username or password is incorrect';
export const EMAIL_NOT_VERIFIED = 'Please verify your email';
export const ACCOUNT_EXISTED = 'This account is already exist';
export const CANNOT_AUTHENTICATE = 'Could not authenticate';
export const ACCOUNT_NOT_FOUND = 'Oops! This account was not found. Please check for mistypes or create a new account';
export const USERNAME_HAS_BEEN_TAKEN = 'This username has been taken, please choose another one';
export const EMAIL_HAS_BEEN_TAKEN = 'This email has been taken, please choose another one';
export const ACCOUNT_INACTIVE = 'This account is deactive';